apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 4
  strategy: {}
  selector:
    matchLabels:
      io.kompose.service: web
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: web
    spec:
      containers:
      - image: app_sec_hw4_web
        imagePullPolicy: Never
        name: web
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "500Mi"
            cpu: 1
        env:
          - name: CSRF_TOKEN
            valueFrom:
              secretKeyRef:
                name: flask-app-secrets
                key: csrf_token
          - name: ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: flask-app-secrets
                key: admin_password
          - name: PHONE_NUMBER
            valueFrom:
              secretKeyRef:
                name: flask-app-secrets
                key: phone_number
      restartPolicy: Always
status: {}
